<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="macbook-pro.local" name="net.binout.codestory2013.HeinRestServiceTest" tests="4" failures="0" timestamp="19 Jan 2013 20:28:12 GMT" time="0.001" errors="1">
  <testcase name="constructor_should_create_calculator" time="0.000" classname="net.binout.codestory2013.HeinRestServiceTest"/>
  <testcase name="constructor_should_load_enonce" time="0.000" classname="net.binout.codestory2013.HeinRestServiceTest"/>
  <testcase name="constructor_should_create_empty_cache" time="0.000" classname="net.binout.codestory2013.HeinRestServiceTest"/>
  <testcase name="postcontruct_should_load_cache" time="0.001" classname="net.binout.codestory2013.HeinRestServiceTest">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at net.binout.codestory2013.HeinRestServiceTest.postcontruct_should_load_cache(HeinRestServiceTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:54)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83)
]]>
    </error>
  </testcase> <!-- postcontruct_should_load_cache -->
</testsuite> <!-- net.binout.codestory2013.HeinRestServiceTest -->
